### ISSUE TITLE
Bad request - 400

### ISSUE THREAD

**Issue by gajicm93** [GoogleCloudPlatform/cloud-vision#106]
I'm using an untouched Android sample, and the API returns me a bad request 400 looking like this:

`{
                                                     "code": 400,
                                                     "message": "Invalid JSON payload received. Unknown name \"c\": Cannot find field.",
                                                     "errors": [
                                                       {
                                                         "message": "Invalid JSON payload received. Unknown name \"c\": Cannot find field.",
                                                         "domain": "global",
                                                         "reason": "badRequest"
                                                       }
                                                     ],
                                                     "status": "INVALID_ARGUMENT"
                                                   }`

The JSON looks like this:

`{c=[{c=[{c=10, d=LABEL_DETECTION}], d={c=_9j_4AAQSkZJRgABAQAAAQABAAD_2wBDAKABQoUKAP_9k}}]}`

I shortened the Base64 image string obviously.

**Comment by gajicm93** [comment]
@tswast @jerjou please guys take me a look at this.

**Comment by yogesh-golande** [comment]
Setting minifyEnabled to false instead of true under build.grade of app module solves the issue.
To be honest, I don't know whether this is just a work around or the right solution.

**Comment by gajicm93** [comment]
@yogesh-golande It's definitely just a workaround, but thanks for pointing that out, I would never guess what the problem was.

**Comment by drewszurko** [comment]
@yogesh-golande setting minifyEnabled to false will disable ProGuard obfuscation and resource shrinking. This is fine when you're working with your debug build (Android Studio disables it by default during debugging). However, if a user plans to use ProGuard in their final build, @gajicm93 issue would still persist.

The problem is ProGuard obfuscates your request fields strings, so when the Cloud Vision API parses your request it can't find the needed fields. For example, `maxResults=10` becomes `c=10`. 

To fix this, you need to update your proguard-rules.pro file to keep the library your using to build your request. For me specifically, I had to include `-keep class com.google.api.services.vision.** { *; }`.

**Comment by gajicm93** [comment]
@drewszurko Yeah that's exactly right, although I think your keep rule is a bit too broad, and will also keep a lot of the stuff that don't have to be kept.. Although that's just fine tuning..
