### ISSUE TITLE
OCR missing some numbers

### ISSUE THREAD

**Issue by kzhang819** [GoogleCloudPlatform/cloud-vision#121]
Hi,

I'm currently running Google vision through Python on an image file attached below.
![try](https://user-images.githubusercontent.com/3460431/28468852-3b7543ee-6e02-11e7-91c7-3098a3abd0b9.png)
Most of the numbers are read, but some numbers are missing. For example, row 16 column 4 value -177 missing. Most of row 15 is missing. There are other errors, but the main point is how to fix this issue? I don't really care about the accuracy of reading the Chinese words. I've tried making the image into black and white, removing background, making it 8 bit, making it binary, and various combinations of them. None achieved perfect recognition of the numbers.

**Comment by cyberdrk** [comment]
What I can suggest is that you can try some image cleaning algorithms ( some pre processing or and some morphological operations like dilation or eroding ) because if you look closely, the lines near the problematic rows are fainter than the ones elsewhere ( I mean that could be a problem ). Just a generic solution.
