### ISSUE TITLE
HttpError 403 when requesting /images:annotate from GCE"

### ISSUE THREAD

**Issue by sprakash3** [GoogleCloudPlatform/cloud-vision#19]
Hi,

I get the following exception when running the example application on GCE. The cloud Vision API has been activated for the project.

Traceback (most recent call last):
  File "vision-test.py", line 35, in <module>
    response = service_request.execute(num_retries=num_retries)
  File "/usr/lib/anaconda/lib/python2.7/site-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/anaconda/lib/python2.7/site-packages/googleapiclient/http.py", line 729, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://vision.googleapis.com/v1/images:annotate?alt=json returned "Project has not activated the vision.googleapis.com API. Please enable the API for project google.com:cloudsdktool (#32555940559).">

Thanks!

**Comment by amygdala** [comment]
This is probably one of two issues.  First, make sure that your GCE instance was created with the "Allow API access to all Google Cloud services in the same project" box ticked, under the "access & security" pane, in the cloud console.

Then, it turns out that there is an issue with the `oauth2client` lib-- version 2.0.0 is broken. That is probably what you have installed. (This will be fixed very soon).
Downgrade to version 1.5.2 of `oauth2client`, after making sure that the instance was set up as above, and things should work.

**Comment by adi-li** [comment]
I got this error before. The reason is the python client didn't get the right project credential.
Please try to follow the [another example](https://github.com/GoogleCloudPlatform/cloud-vision/tree/master/python/text#set-up-to-authenticate-with-your-projects-credentials) to solve the error.

Here is what I did:
1. Create service account key JSON file in [Google Cloud Console](https://console.cloud.google.com)
2. Save the credential JSON file in a secure place
3. Set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to point to the JSON file.

**Comment by sprakash3** [comment]
Thanks. Works with `oauth2client` lib version 2.0.1 now.
