### ISSUE TITLE
KeyError: 'faceAnnotations' on images not containing any faces

### ISSUE THREAD

**Issue by muglikar** [GoogleCloudPlatform/cloud-vision#89]
When I pass an image containing no faces, I should get 0 as a result, instead I get this:

`faces = response['responses'][0]['faceAnnotations']
KeyError: 'faceAnnotations'
`

I'm using your python code for face detection. And I'm not sure every one of my images will contain a face or not.
![shenga](https://cloud.githubusercontent.com/assets/332364/18229754/d2a389b8-72a1-11e6-88e4-67ea7ca51df5.jpg)

**Comment by tswast** [comment]
Hi @muglikar, thanks for the report. The problem is that the Vision API (or any other recent Google Cloud API) does not send back an empty list when it is empty in the response. Choosing instead to omit values when they are set to the default value. (I think you might notice that an offset of 0 is never sent as well.)

I will file a bug internally to track this issue, as I agree that it is confusing behavior.

**Comment by jerjou** [comment]
(In the meantime, you can add a check in your code to make sure the 'faceAnnotations' key exists before using it)

**Comment by muglikar** [comment]
@tswast Thanks for the reply, but the same problem arises for `KeyError: 'labelAnnotations'` when GCV API is unable to put a label to an image it encounters. There has to be some simple solution to this behavior as we are not certain beforehand that GCV will send error for an image for which it couldn't find any labels. Same thing happens if the labels/faces returned by GCV are less than the max_labels or max_faces respectively queried to it. 

Can we as a community of GCV API users expect to see a solution to this? Especially when we're automating the labeling/face detection process using code to query GCV API. 

Thanks and thanks in advance for the internal bug to fix this issue.

@jerjou I mean how can I judge or anticipate for a batch of images, that Google CV API will send an error, when an image will fetch empty reply= with a keyerror, beforehand? Of course my code has a 'faceAnnotations' key and a 'labelAnnotations' key.

Actually, doesn't this behavior defeat the whole purpose of _face detection_ when you have to first manually check if the image contains face(s)? It should return, something that can say that the image has returned with no faces or no labels found or less than the number of max_faces/max_labels/default instead of giving a rather disappointing error.

**Comment by muglikar** [comment]
@yehangjun Any comments?

**Comment by jerjou** [comment]
I think you misunderstand me. As far as I can tell, the current problem is that, if there are no faces detected, the API will return a list of one empty element (ie `[{}]`) instead of an empty list (ie `[]`). When the python client code sees the element, it assumes that it has a certain structure - namely, that there's a 'faceAnnotations' key.

What I'm suggesting is, while we're waiting for the server side to change to return an empty list in this case, you can add an additional check to the client code, to make sure the returned object actually has the key you're trying to reference. That is, this code:

```py
faces = response['responses'][0]['faceAnnotations']
```

could be changed into something like this:

```py
if response['responses'] and 'faceAnnotations' in response['responses'][0]:
    faces = response['responses'][0]['faceAnnotations']
```

Does that make sense? You're not manually checking the image itself for faces. You're verifying that the response the api returns contains the key you expect.
